-- Дальняя связь усиливает существующие и новые обычные подлодки.
INSERT INTO Requirements (RequirementId, RequirementType)
VALUES ('BBC_REQUIRE_SUBMARINE', 'REQUIREMENT_UNIT_TYPE_MATCHES');
INSERT INTO RequirementArguments (RequirementId, Name, Value)
VALUES ('BBC_REQUIRE_SUBMARINE', 'UnitType', 'UNIT_SUBMARINE');
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES ('BBC_SUBMARINE_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES ('BBC_SUBMARINE_REQUIREMENTS', 'BBC_REQUIRE_SUBMARINE');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('BBC_SUBMARINE_TELECOM_STRENGTH', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH', 'BBC_SUBMARINE_REQUIREMENTS'),
('BBC_SUBMARINE_TELECOM_ATTACH_SIGHT', 'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER', 'BBC_SUBMARINE_REQUIREMENTS');
INSERT INTO Modifiers (ModifierId, ModifierType)
VALUES ('BBC_SUBMARINE_TELECOM_SIGHT', 'MODIFIER_PLAYER_UNIT_ADJUST_SIGHT');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('BBC_SUBMARINE_TELECOM_STRENGTH', 'Amount', '5'),
('BBC_SUBMARINE_TELECOM_ATTACH_SIGHT', 'ModifierId', 'BBC_SUBMARINE_TELECOM_SIGHT'),
('BBC_SUBMARINE_TELECOM_SIGHT', 'Amount', '1');
INSERT INTO TechnologyModifiers (TechnologyType, ModifierId) VALUES
('TECH_TELECOMMUNICATIONS', 'BBC_SUBMARINE_TELECOM_STRENGTH'),
('TECH_TELECOMMUNICATIONS', 'BBC_SUBMARINE_TELECOM_ATTACH_SIGHT');

-- Дальняя связь: +1 к обзору существующих и новых эсминцев.
INSERT INTO Requirements (RequirementId, RequirementType)
VALUES ('BBC_REQUIRE_DESTROYER', 'REQUIREMENT_UNIT_TYPE_MATCHES');
INSERT INTO RequirementArguments (RequirementId, Name, Value)
VALUES ('BBC_REQUIRE_DESTROYER', 'UnitType', 'UNIT_DESTROYER');
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES ('BBC_DESTROYER_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES ('BBC_DESTROYER_REQUIREMENTS', 'BBC_REQUIRE_DESTROYER');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
VALUES ('BBC_DESTROYER_TELECOM_ATTACH_SIGHT', 'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER', 'BBC_DESTROYER_REQUIREMENTS');
INSERT INTO Modifiers (ModifierId, ModifierType)
VALUES ('BBC_DESTROYER_TELECOM_SIGHT', 'MODIFIER_PLAYER_UNIT_ADJUST_SIGHT');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('BBC_DESTROYER_TELECOM_ATTACH_SIGHT', 'ModifierId', 'BBC_DESTROYER_TELECOM_SIGHT'),
('BBC_DESTROYER_TELECOM_SIGHT', 'Amount', '1');
INSERT INTO TechnologyModifiers (TechnologyType, ModifierId)
VALUES ('TECH_TELECOMMUNICATIONS', 'BBC_DESTROYER_TELECOM_ATTACH_SIGHT');
